### ISSUE TITLE
do not require DJANGO_SETTINGS_MODULE when running pytest help

### ISSUE THREAD

**Issue by piotr-kubiak** [pytest-dev/pytest-django#1144]
Is it really necessary to require seting `DJANGO_SETTINGS_MODULE` only to display help?
I run my tests using `tox`, and `DJANGO_SETTINGS_MODULE` is being set there.
Sometimes I just need to quickly run `pytest help` just to see some syntax.
Does the output of `pytest help` depend on my currently configured settings?

My current output:
```
$ pytest --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "H:\python\django-pytest\.venv\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
           ^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 341, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
    self.parse(args)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1490, in parse
    self._preparse(args, addopts=addopts)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1394, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\warnings.py", line 151, in pytest_load_initial_conftests
    return (yield)
            ^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\capture.py", line 154, in pytest_load_initial_conftests
    yield
  File "H:\python\django-pytest\.venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 1218, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 581, in _set_initial_conftests
    self._try_load_conftest(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 619, in _try_load_conftest
    self._loadconftestmodules(
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 659, in _loadconftestmodules
    mod = self._importconftest(
          ^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 735, in _importconftest
    self.consider_conftest(mod, registration_name=conftestpath_plugin_name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 816, in consider_conftest
    self.register(conftestmodule, name=registration_name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 512, in register
    self.consider_module(plugin)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 824, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 831, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\config\__init__.py", line 858, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "H:\python\django-pytest\.venv\Lib\site-packages\_pytest\assertion\rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "h:\python\django-pytest\test_fixtures.py", line 11, in <module>
    from django_pytest_app.models import (
  File "H:\python\django-pytest\django_pytest_app\models.py", line 5, in <module>
    class Foo(models.Model):
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\db\models\base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\apps\registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\apps\registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\conf\__init__.py", line 81, in __getattr__
    self._setup(name)
  File "H:\python\django-pytest\.venv\Lib\site-packages\django\conf\__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by webknjaz** [comment]
That exception is coming from Django, not this plugin. I'd imagine that I help does not need to show anything from Django imports, it'd be okay to suppress said import/call..

P.S. You only included 3 lines from the bigger traceback. It wouldn't be possible to judge where to intercept the error without that info.

**Comment by piotr-kubiak** [comment]
Sorry, my bad. I assumed it was related to me installing pytest-django.
I've removed the stack trace, because I also assumed that someone needs to reproduce it either way.
I've edited the post.

**Comment by bluetech** [comment]
The pytest-django plugin itself is careful to not initialize django on stuff like `--help` (there is a test verifying this).

In your case the problem comes from here:

```
  File "h:\python\django-pytest\test_fixtures.py", line 11, in <module>
    from django_pytest_app.models import (
```

pytest on startup looks for plugins which one way or another causes this file to be imported, and import Django models require Django to be initialized.

**Comment by piotr-kubiak** [comment]
I'll file this request with pytest then.
Error in the import phase should not prevent pytest from displaying help in my opinion.
