### ISSUE TITLE
Plugin stops testing non-django projects

### ISSUE THREAD

**Issue by flub** [pytest-dev/pytest-django#3]
Hi

When the plugin is installed testing a non-django project without having DJANGO_SETTINGS_MODULE results in an error.  The reason (AFAIK) is that pytest_django.plugin, which is registered as the pytest11 entrypoint via "from .plugin import *" in pytest_django.**init**, does a direct "from django.conf import settings".

I'm not immediately sure how the plugin can detect it is testing a django application in order to decide to activate itself or not.  But I think it would be beneficial to not have pytest-django break normal test runs by default.

Regards,
Floris

**Comment by ask** [comment]
Doesn't look like this is fixed for all cases, as `pytest-django` is still calling `django.setup()` which breaks non-Django projects:

```

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/_pytest/config.py", line 839, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/pytest_django/plugin.py", line 251, in pytest_configure
INTERNALERROR>     _setup_django()
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/pytest_django/plugin.py", line 134, in _setup_django
INTERNALERROR>     django.setup()
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
INTERNALERROR>     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
INTERNALERROR>     self._setup(name)
INTERNALERROR>   File "/Users/asksol/.virtualenvs/def/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
INTERNALERROR>     % (desc, ENVIRONMENT_VARIABLE))
INTERNALERROR> ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by pelme** [comment]
@ask Are you sure you are not accidentally importing from django somewhere during test collection? We do check that you actually imported Django and configured Django before calling `django.setup()`: https://github.com/pytest-dev/pytest-django/blob/e540acef62fe4a672b52dbc63b14ce4990d00c5b/pytest_django/plugin.py#L137-L148

I did a quick test but was not able to reproduce the problem:

```
‹tempenv-260c13716655c› ~/empty → pip install pytest pytest-django django
Downloading/unpacking pytest
  Downloading pytest-3.0.0-py2.py3-none-any.whl (168kB): 168kB downloaded
Downloading/unpacking pytest-django
  Downloading pytest_django-2.9.1-py2.py3-none-any.whl
Downloading/unpacking django
  Downloading Django-1.10-py2.py3-none-any.whl (6.8MB): 6.8MB downloaded
Downloading/unpacking py>=1.4.29 (from pytest)
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB): 81kB downloaded
Installing collected packages: pytest, pytest-django, django, py
Successfully installed pytest pytest-django django py
Cleaning up...
‹tempenv-260c13716655c› ~/empty → echo 'def test_foo():pass'>test_foo.py
‹tempenv-260c13716655c› ~/empty → pytest
================================================= test session starts ==================================================
platform darwin -- Python 2.7.10, pytest-3.0.0, py-1.4.31, pluggy-0.3.1
rootdir: /Users/andreas/empty, inifile:
plugins: django-2.9.1
collected 1 items

test_foo.py .

=============================================== 1 passed in 0.01 seconds ===============================================
‹tempenv-260c13716655c› ~/empty →
```

Please get back with more info on how to reproduce and I will look into it!
