### ISSUE TITLE
_django_db_setup fails with data migrations

### ISSUE THREAD

**Issue by kuboschek** [pytest-dev/pytest-django#341]
## Situation

In my project, I have a data migration that transfers one value of a certain model to another property of the same model. During test setup, all migrations are run as per default fixture of pytest. 
## Expected behavior

pytest-django runs all migrations, including data migrations
## Actual behavior

All tests end with errors, due to DB use being disallowed during test setup
## Versions

platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
django settings: project.mysite.settings.local (from ini file)
rootdir: /vagrant, inifile: pytest.ini
plugins: django-2.9.1, pythonpath-0.7
## Possible resolution

Is there a way of still using that default fixture, but allowing DB access, or not running this specific migration?

**Comment by pelme** [comment]
Without seeing the code and exception traceback, it is very hard to figure out what is going on and what the problem is.

Please provide steps and information for how to reproduce the error. A PR with a test case that shows the issue would of course be even better and increase the chance that we can get the issue fixed faster. :)

**Comment by tovmeod** [comment]
I'm having a similar issue, maybe it is caused by the same bug.

I have a data migration providing initial value for a model, populating the table.

When running old style unittest Class based tests it runs correctly

When running a parametrized test it doesn't apply the data migration, causing the test to fail.

Below is the test:

@pytest.mark.skipif(os.environ.get('SELENIUM', False), reason='Selenium env is set to 1')
@pytest.mark.parametrize('url', _get_noargs_urls())
@pytest.mark.django_db(transaction=True)
def test_no_args_urls_loggedin(url, client, userpsw):
    """All URLs without arguments should return 200 if logged in"""
    user, psw = userpsw
    client.login(username=user, password=psw)
    response = client.get(url)
    # assert response.status_code == 200

Can I tell it to force running migrations?

**Comment by davo-pkools** [comment]
I think I have a similar situation - essentially it appears the migration is applied to the database after completion of the first test case, before execution of the second. This code demonstrates the issue I am seeing:

```
import pytest
from django.core.management import call_command
from foo import bar

@pytest.fixture(scope='session')
def django_db_setup(django_db_setup, django_db_blocker):
    LOGGER.info('ran call_command')
    with django_db_blocker.unblock():
        call_command('loaddata', 'XXX.json')

@pytest.mark.django_db(transaction=True)
def test_t1():
    assert len(bar.objects.all())

@pytest.mark.django_db(transaction=True)
def test_t2():
    assert len(bar.objects.all())
```

The test fixture XXX.json includes one bar. The first test (test_t1) succeeds. The second test (test_t2) fails. It appears that the transaction=True attribute does not result in the database being reinitialized with the data from the test fixture.

If TransactionTestCase from unittest is used instead, an example that replicates the intent shows the initialization happens before every test case in the class and all tests succeed.

```
from django.test import TransactionTestCase
from foo import bar
class TestOne(TransactionTestCase):

    fixtures = ['XXX.json']

    def test_tc1(self):
        assert len(bar.objects.all())

    def test_tc2(self):
        assert len(bar.objects.all())
        objs = bar.objects.all()
        for bar in objs:
            bar.delete()

    def test_tc3(self):
        assert len(bar.objects.all())
```

**Comment by sconstable** [comment]
We have also been bitten by this. See the attached stack trace:
```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
cachedir: .tox/py36/.pytest_cache
Django settings: settings.test_gitlab (from command line option)
rootdir: /builds/company/project, inifile: pytest.ini
plugins: pycharm-0.5.0, mock-1.10.3, django-3.4.8, cov-2.6.1
collected 480 items

core/tests/test_mail.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 78, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 87, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 175, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/skipping.py", line 127, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 249, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/reports.py", line 364, in from_item_and_call
INTERNALERROR>     excinfo, style=item.config.option.tbstyle
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/nodes.py", line 285, in _repr_failure_py
INTERNALERROR>     truncate_locals=truncate_locals,
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 552, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 802, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 747, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 706, in repr_traceback_entry
INTERNALERROR>     reprargs = self.repr_args(entry) if not short else None
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 624, in repr_args
INTERNALERROR>     args.append((argname, self._saferepr(argvalue)))
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 618, in _saferepr
INTERNALERROR>     return saferepr(obj)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 72, in saferepr
INTERNALERROR>     return srepr.repr(obj)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 12, in repr
INTERNALERROR>     return self._callhelper(reprlib.Repr.repr, self, x)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 38, in _callhelper
INTERNALERROR>     s = call(x, *args)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/reprlib.py", line 55, in repr
INTERNALERROR>     return self.repr1(x, self.maxlevel)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/reprlib.py", line 65, in repr1
INTERNALERROR>     return self.repr_instance(x, level)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 33, in repr_instance
INTERNALERROR>     return self._callhelper(repr, x)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 38, in _callhelper
INTERNALERROR>     s = call(x, *args)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __repr__
INTERNALERROR>     data = list(self[:REPR_OUTPUT_SIZE + 1])
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
INTERNALERROR>     self._fetch_all()
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
INTERNALERROR>     self._result_cache = list(self._iterable_class(self))
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
INTERNALERROR>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1095, in execute_sql
INTERNALERROR>     cursor = self.connection.cursor()
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
INTERNALERROR>     return self._cursor()
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
INTERNALERROR>     self.ensure_connection()
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/pytest_django/plugin.py", line 749, in _blocking_wrapper
INTERNALERROR>     "Database access not allowed, "
INTERNALERROR>   File "/builds/company/project/.tox/py36/lib/python3.6/site-packages/_pytest/outcomes.py", line 117, in fail
INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
INTERNALERROR> Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```

**Comment by blueyed** [comment]
@sconstable 
Looks like https://github.com/pytest-dev/pytest-django/issues/713.

**Comment by ericholscher** [comment]
I'm still hitting this with the latest pytest & pytest-django:

```
========================================================= test session starts ==========================================================
platform darwin -- Python 3.6.5, pytest-5.2.2, py-1.8.1, pluggy-0.13.1
cachedir: .tox/py36/.pytest_cache
Django settings: readthedocs.settings.test (from environment variable)
rootdir: /Users/eric/projects/readthedocs.org, inifile: pytest.ini
plugins: django-3.6.0, xdist-1.30.0, mock-1.11.2, custom-exit-code-0.3.0, celery-4.1.1, forked-1.1.3, cov-2.8.1
collected 1674 items / 234 deselected / 1440 selected

core/tests/test_signals.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 193, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 237, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 258, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 80, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 89, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 178, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/skipping.py", line 123, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/runner.py", line 252, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/reports.py", line 282, in from_item_and_call
INTERNALERROR>     excinfo, style=item.config.getoption("tbstyle", "auto")
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/nodes.py", line 299, in _repr_failure_py
INTERNALERROR>     truncate_locals=truncate_locals,
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 597, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 829, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 777, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 736, in repr_traceback_entry
INTERNALERROR>     reprargs = self.repr_args(entry) if not short else None
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_code/code.py", line 655, in repr_args
INTERNALERROR>     args.append((argname, saferepr(argvalue)))
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 67, in saferepr
INTERNALERROR>     return SafeRepr(maxsize).repr(obj)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 36, in repr
INTERNALERROR>     s = super().repr(x)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/reprlib.py", line 55, in repr
INTERNALERROR>     return self.repr1(x, self.maxlevel)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/reprlib.py", line 65, in repr1
INTERNALERROR>     return self.repr_instance(x, level)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/_io/saferepr.py", line 43, in repr_instance
INTERNALERROR>     s = repr(x)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __repr__
INTERNALERROR>     data = list(self[:REPR_OUTPUT_SIZE + 1])
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
INTERNALERROR>     self._fetch_all()
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
INTERNALERROR>     self._result_cache = list(self._iterable_class(self))
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
INTERNALERROR>     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
INTERNALERROR>     cursor = self.connection.cursor()
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
INTERNALERROR>     return self._cursor()
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
INTERNALERROR>     self.ensure_connection()
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/pytest_django/plugin.py", line 778, in _blocking_wrapper
INTERNALERROR>     "Database access not allowed, "
INTERNALERROR>   File "/Users/eric/projects/readthedocs.org/.tox/py36/lib/python3.6/site-packages/_pytest/outcomes.py", line 128, in fail
INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
INTERNALERROR> Failed: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```

 The problem seems to be a data migration:

https://github.com/readthedocs/readthedocs.org/blob/8c13dc1e4e61a0229793ef6f76f05b1d7bd50b51/readthedocs/projects/migrations/0050_migrate_external_builds.py#L6-L12

When I add a `return` at the top of this migration it stops happening.
