### ISSUE TITLE
django.db.utils.OperationalError if execute query in apps.ready

### ISSUE THREAD

**Issue by pacahon** [pytest-dev/pytest-django#398]
Hello, needs help.
If I execute query in [ready](https://docs.djangoproject.com/en/1.10/ref/applications/#django.apps.AppConfig.ready) method, `pytest` fails with `django.db.utils.OperationalError: no such table`, while `manage.py runserver` works fine. Django documentation says, it should works fine also.
https://docs.djangoproject.com/en/1.10/ref/applications/#how-applications-are-loaded

Traceback:

```bash
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/csc/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/config.py", line 46, in main
    config = _prepareconfig(args, plugins)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/config.py", line 131, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/config.py", line 881, in pytest_cmdline_parse
    self.parse(args)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/config.py", line 1037, in parse
    self._preparse(args, addopts=addopts)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/config.py", line 1008, in _preparse
    args=args, parser=self._parser)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/pytest_django/plugin.py", line 245, in pytest_load_initial_conftests
    _setup_django()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/pytest_django/plugin.py", line 148, in _setup_django
    django.setup()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/user/websites/myproject/notifications/apps.py", line 17, in ready
    self.module.autodiscover()
  File "/home/user/websites/myproject/notifications/__init__.py", line 92, in autodiscover
    autodiscover_modules('notifications', register_to=registry)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/user/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/user/websites/myproject/learning/projects/notifications.py", line 10, in <module>
    print(Type.objects.all())
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/models/query.py", line 234, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/py34/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: notifications_type
```

**Comment by pacahon** [comment]
Error occurs on Django 1.9.x

**Comment by pacahon** [comment]
I realized it's a bad idea to execute queryset in `apps.ready`.
