### ISSUE TITLE
Check for deprecation warnings in our test suite / CI

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-django#415]
See #393 and #395 for warnings that we missed. We need a way to make sure we put out warning-free releases.

**Comment by blueyed** [comment]
Via pytest-warnings maybe?
https://github.com/pytest-dev/pytest-django/pull/395#issuecomment-247759965

Just using `-Werror` fails with the stdlib already:
```
Failed to import the site module
Traceback (most recent call last):
  File "…/pyenv/tmp-pytest-django-adi6OX/lib/python3.5/site.py", line 706, in <module>
    main()
  File "…/pyenv/tmp-pytest-django-adi6OX/lib/python3.5/site.py", line 686, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "…/pyenv/tmp-pytest-django-adi6OX/lib/python3.5/site.py", line 285, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "…/pyenv/tmp-pytest-django-adi6OX/lib/python3.5/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "…/pyenv/tmp-pytest-django-adi6OX/lib/python3.5/site.py", line 168, in addpackage
    f = open(fullname, "rU")
DeprecationWarning: 'U' mode is deprecated
```

I could imagine to add some logfilter for this, but then it's probably what pytest-warnings does already?!

**Comment by pelme** [comment]
I haven't looked into it but we need something that fails CI on deprecation warnings in Django or pytest. Hopefully pytest-warnings does that out of the box. :)
