### ISSUE TITLE
no warning/error if exception occurs in your settings.py

### ISSUE THREAD

**Issue by cjw296** [pytest-dev/pytest-django#512]
It appears that the exception is just swallowed, which creates very weird behaviour if you settings are mostly loaded, but partly not because execution of your test settings.py fails half way though.

**Comment by pelme** [comment]
Can you please provide some more information and some way to reproduce this?

This is what happens for me when I raise an exception in my settings file (i.e. the full exception traceback is shown and the root of the exception is shown):

```traceback
~/code/myproject → pytest
Traceback (most recent call last):
  File "/Users/andreas/code/myproject/venv-3.6/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/config.py", line 168, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/config.py", line 1092, in _preparse
    args=args, parser=self._parser)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/pytest_django/plugin.py", line 244, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/andreas/code/myproject/venv-3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/andreas/code/myproject/proj/conf/settings/tests.py", line 1, in <module>
    from .base import *  # flake8: noqa
  File "/Users/andreas/code/myproject/proj/conf/settings/base.py", line 424, in <module>
    raise ValueError('foo')
ValueError: foo

```

**Comment by cjw296** [comment]
My mistake, after a huge amount of debugging it turns out DJANGO_SETTINGS_MODULE was being used from an environment variable, rather than my pytest.ini, and so lead me to believe the above.
Apologies for not closing this sooner.
