### ISSUE TITLE
"ModuleNotFoundError: No module named 'tests'" when using "src" directory

### ISSUE THREAD

**Issue by sscherfke** [pytest-dev/pytest-django#738]
I have a small [Django app](https://gitlab.com/sscherfke/django-sphinxdoc) that I test with pytest-django.  The app’s package is in `sphinxdoc`, the tests are in `tests` and the Django settings modules for the tests is in `tests.settings`.

When I move the app's package to `src/sphinxdoc`, the tests no longer run:
```
Traceback (most recent call last):
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pytest_django/plugin.py", line 166, in _handle_import_error
    yield
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pytest_django/plugin.py", line 333, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/_pytest/config/__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/_pytest/config/__init__.py", line 204, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/_pytest/config/__init__.py", line 684, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/_pytest/config/__init__.py", line 901, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/_pytest/config/__init__.py", line 856, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pytest_django/plugin.py", line 333, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/stefan/.virtualenvs/django-sphinxdoc/lib/python3.7/site-packages/pytest_django/plugin.py", line 170, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'tests'
```
At the point where pytest/django tries to import `tests.settings` only the project’s `/src` dir is in the Python path. The project's root dir `/` seems to be added later since usually an import like `import tests.spam` from another test works, even when the tested package lives in `/src`.

**Comment by madnesspie** [comment]
I have the same issue. Does any solution exist?

**Comment by Ravi9562** [comment]
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Testdjango'

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 599, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 584, in start_django
    reloader.run(django_main_thread)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 299, in run
    self.run_loop()
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 305, in run_loop
    next(ticker)
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 345, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 361, in snapshot_files
    for file in self.watched_files():
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 260, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 105, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Python\Python37\lib\site-packages\django-3.0.4-py3.7.egg\django\utils\autoreload.py", line 141, in iter_modules_and_files
    resolved_path = path.resolve(strict=True).absolute()
  File "C:\Python\Python37\lib\pathlib.py", line 1161, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Python\Python37\lib\pathlib.py", line 200, in resolve
    return self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'


I am getting below error. Please help me in this regard. I am using python 3.7. Django 3.0.4. Please do let me know if you need more details

**Comment by blueyed** [comment]
Try using `python -m pytest` instead of `pytest`.

**Comment by Ravi9562** [comment]
> Try using `python -m pytest` instead of `pytest`.
> (more related to the first two comments, but worth a try for the latest one also)

Hello I am not running pytest. But I am running below command
python manage.py runserver

**Comment by blueyed** [comment]
@Ravi9562 
Oh, yeah - completely unrelated.
You could try printing / debugging it from `C:\Python\Python37\lib\pathlib.py", line 20` I guess (to find the path causing it.
It's an issue with Django or Python though, so please ask for help there then.

**Comment by blueyed** [comment]
@sscherfke @madnesspie 
Please try `python -m pytest`.
It could also be related to the scanning for manage.py that exists within pytest-django, so also try to look at / for that.

**Comment by bluetech** [comment]
Closing as needs-info. I can reopen if there are more details.

**Comment by browniebroke** [comment]
I had the same issue and I fixed it by using [`pytest-pythonpath/`](https://pypi.org/project/pytest-pythonpath/) and configuring it as follows:

```toml
# pyproject.toml
[tool.pytest.ini_options]
pythonpaths = ["src", "."]
```

Hope it helps others with the same problem.

**Comment by browniebroke** [comment]
There is already a mention of this package [in the docs](https://pytest-django.readthedocs.io/en/latest/managing_python_path.html#using-pytest-pythonpath), is this use case common enough to justify giving an example? I see that pytest 7 will introduce [a built-in `pythonpath` setting](https://github.com/pytest-dev/pytest/pull/9134) for that.

**Comment by bluetech** [comment]
@browniebroke A PR for this would be great!

**Comment by Kirade** [comment]
In my case, I was making django app as a package. and same error happend.

Originally, my django app package was look like this.
```
 myproj
    ├── pytest.ini
    ├── src
    │   └── myapp
    │       ├── __init__.py
    │       ├── models.py
    │       └── app.py
    └── tests
        ├── testapp
        |   ├── __init__.py
        |   └── apps.py
        ├── __init__.py
        ├── settings.py
        └── test_main.py
```

To solve this problem, I took advantage of pytest-django's [automatic looking for django project](https://pytest-django.readthedocs.io/en/latest/managing_python_path.html#automatic-looking-for-of-django-projects) feature.

After I simply put manage.py in project root, pytest works great.
```
 myproj
    ├── pytest.ini
    ├── manage.py  <-- Added
    ├── src
    │   └── myapp
    │       ├── __init__.py
    │       ├── models.py
    │       ├── views.py
    │       └── app.py
    └── tests
        ├── __init__.py
        ├── settings.py
        ├── test_views.py
        └── test_models.py
```

**Comment by perymerdeka** [comment]
di you have a example for src project
