### ISSUE TITLE
Tests do not run without django-configuration installed.

### ISSUE THREAD

**Issue by jakubjanuzik** [pytest-dev/pytest-django#790]
In my project I do not use django-configuration as I don't really need it.

When installing `pytest-django` I try to run my tests, here's what I've got:
```
pytest  
Traceback (most recent call last):
  File "/home/jakub/.virtualenvs/mobigol/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 72, in main
    config = _prepareconfig(args, plugins)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 223, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 742, in pytest_cmdline_parse
    self.parse(args)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 948, in parse
    self._preparse(args, addopts=addopts)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 906, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pytest_django/plugin.py", line 239, in pytest_load_initial_conftests
    import configurations.importer
ModuleNotFoundError: No module named 'configurations'
```

Also my package versions:
```
pytest==5.3.1
pytest-django==3.3.0
pytest-factoryboy==2.0.3
```

Is `django-configuration` required? I couldn't find any information about it in the documentation.

**Comment by blueyed** [comment]
I think it should work without it.

Something appears to trigger the import for you though: https://github.com/pytest-dev/pytest-django/blob/00e7beed6af794823dc5bd56fa7307d3ccc32da9/pytest_django/plugin.py#L312-L328
(also your line number is very different, so please try the latest release / master branch)

I think a fix would be to ignore/handle the ImportError here though, too.

**Comment by jakubjanuzik** [comment]
I do have set `DJANGO_SETTINGS_MODULE` in my `pytest.ini`, could this be the cause?
```
cat pytest.ini 
[pytest]
DJANGO_SETTINGS_MODULE = mobigol.test_settings
python_files = tests.py test_*.py *_tests.py
```

`test_settings.py` (just to have separate file for now).

```from django.conf import settings

from .settings import *
```

Updated the lib:
```pip freeze | grep pytest
pytest==5.3.1
pytest-django==3.7.0
pytest-factoryboy==2.0.3
```

But the error still happens:
```
 pytest
Traceback (most recent call last):
  File "/home/jakub/.virtualenvs/mobigol/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 72, in main
    config = _prepareconfig(args, plugins)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 223, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 742, in pytest_cmdline_parse
    self.parse(args)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 948, in parse
    self._preparse(args, addopts=addopts)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/_pytest/config/__init__.py", line 906, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jakub/.virtualenvs/mobigol/lib/python3.6/site-packages/pytest_django/plugin.py", line 326, in pytest_load_initial_conftests
    import configurations.importer
ModuleNotFoundError: No module named 'configurations'
```

The line number seems to be correct this time though.

**Comment by blueyed** [comment]
Can you check which of the options triggers it, please?
https://github.com/pytest-dev/pytest-django/blob/00e7beed6af794823dc5bd56fa7307d3ccc32da9/pytest_django/plugin.py#L313-L317
(using pdb or just `print`)

> I do have set `DJANGO_SETTINGS_MODULE` in my `pytest.ini`, could this be the cause?

Shouldn't be an issue.

**Comment by jakubjanuzik** [comment]
I found the cause, in my another project (from the job) we use Django-Configurations and I had set `DJANGO_CONFIGURATION` environment variable. That probably triggered the django-configurations for pytest.

After I unset that, everything works as supposed to. 

Thanks for help and sorry for confusion and taking your time

**Comment by blueyed** [comment]
I've thought about handling the ImportError there better, but e.g. turning it into a `pytest.UsageError` is not really that helpful either.
Instead I've thought that the "configuration" being used should be reported (similar to settings): https://github.com/pytest-dev/pytest-django/pull/791.
What do you think?

**Comment by jmarrec** [comment]
I know it's 5 years later, but I stumbled upon this issue while googling, so in the hope that it serves for someone else:

I had copied the pyproject.toml from a project where I did use django-configuration. And the issue was that it had an incorrect `--ds` argument

```diff
[tool.pytest.ini_options]
-addopts = "--ds=config.settings.test --reuse-db --import-mode=importlib"
+addopts = "--ds=myproject.settings --reuse-db --import-mode=importlib"
```
