### ISSUE TITLE
VSCode can't find my tests

### ISSUE THREAD

**Issue by staticdev** [pytest-dev/pytest-django#851]
I've followed the documentation, but when I use test discovery from VSCode I get:

```
Traceback (most recent call last):
  File "/home/static/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/pyvsc-run-isolated.py", line 25, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "/home/static/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/static/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/static/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pytest/__main__.py", line 7, in <module>
    raise SystemExit(pytest.main())
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 105, in main
    config = _prepareconfig(args, plugins)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 257, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/_pytest/helpconfig.py", line 90, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 836, in pytest_cmdline_parse
    self.parse(args)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1044, in parse
    self._preparse(args, addopts=addopts)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1001, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pytest_django/plugin.py", line 323, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/home/static/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/static/.cache/pypoetry/virtualenvs/django-pagination-bootstrap--rMs3NjZ-py3.8/lib/python3.8/site-packages/pytest_django/plugin.py", line 174, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'tests'

pytest-django could not find a Django project (no manage.py file could be found). You must explicitly add your Django project to the Python path to have it picked up.
Error: TypeError: Cannot read property 'testsuites' of null
```

My pytest.ini correctly points to tests.settings file.

**Comment by bluetech** [comment]
Are you able to run it from the command line?

**Comment by staticdev** [comment]
@bluetech yes I can.

**Comment by bluetech** [comment]
So this looks like some issue with the current working directory or PYTHONPATH setting that vscode is setting. Try to play with the `python.pythonPath` vscode setting or similar. Make sure your `tests` module is visible, and that pytest-django can find the django project.
